import { Resend } from "resend";

const resend = process.env.RESEND_API_KEY
  ? new Resend(process.env.RESEND_API_KEY)
  : null;

export async function sendAuditEmail(
  email: string,
  auditUrl: string,
  savings: number
) {
  if (!resend) {
    console.log(
      `[DEV] Would send email to ${email} — audit: ${auditUrl}, savings: $${savings}/mo`
    );
    return { success: true, dev: true };
  }

  try {
    await resend.emails.send({
      from: "StackSight AI <audit@stacksight.ai>",
      to: email,
      subject: "Your AI Spend Audit Report — StackSight AI",
      html: `
        <div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;background:#07080d;color:#e8eaed;padding:40px;border-radius:12px">
          <h1 style="font-size:28px;margin:0 0 8px;color:#fff">Your AI Spend Audit</h1>
          <p style="color:#8b8fa3;margin:0 0 24px">Generated by StackSight AI</p>
          <div style="background:rgba(0,230,118,0.1);border:1px solid rgba(0,230,118,0.2);border-radius:8px;padding:20px;text-align:center;margin-bottom:24px">
            <p style="margin:0 0 4px;color:#8b8fa3;font-size:14px">Potential Monthly Savings</p>
            <p style="margin:0;font-size:36px;font-weight:800;color:#00e676">$${savings}</p>
          </div>
          <a href="${auditUrl}" style="display:block;text-align:center;background:linear-gradient(135deg,#6c5ce7,#a855f7);color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:600">View Full Report</a>
          <p style="color:#8b8fa3;font-size:13px;margin-top:24px;text-align:center">Thanks for using StackSight AI.</p>
        </div>`,
    });
    return { success: true };
  } catch (error) {
    console.error("Failed to send email:", error);
    return { success: false, error };
  }
}
